// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://upftqmajplqdyvinzkqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZnRxbWFqcGxxZHl2aW56a3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MDk0NTEsImV4cCI6MjA3OTk4NTQ1MX0.AqlEJfwEPcUZ97M2Dpe4FgWymQw-Nhtg_copT10w4B0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);